#!/bin/bash
# The script should be invoked as "cbr2cbz {directory}", where "{directory}" is the
# top-level directory to be searched. Just to be paranoid, if no directory is specified,
# then default to the current working directory ("."). Let's put the name of the
# directory into a shell variable called SOURCEDIR.
# Note: "$1" = "The first command line argument"

clear
# Log STOUT to file
[[ -f "comic.log" ]] && rm "comic.log"
exec > >(tee comic.log)

echo
echo "Converting CBRs to CBZs"

IFS="|"

# This directory will be created under SOURCEDIR
TEMPDIR=".r2z_tmp"
[[ -d "$TEMPDIR" ]] && rm -rf $TEMPDIR

if test -z "$1"; then
        SOURCEDIR=`pwd`
else
        SOURCEDIR="$1"
fi

echo
echo "+ Working from directory $SOURCEDIR"

cd "$SOURCEDIR"
mkdir "$TEMPDIR"
cd "$TEMPDIR"

find "$SOURCEDIR" -name "*.cbr" | while read CBRFILE; do

BASENAME=`basename $CBRFILE ".cbr"`

# And the directory path for the finished ".cbz" file.
DIRNAME=`dirname $CBRFILE`

# Now, build the "new" file name,
NEWNAME="$BASENAME.cbz"

echo
echo "> Processing: $BASENAME"
mkdir "$BASENAME"
echo "-> Extracting"
7z x "$CBRFILE" -O"$BASENAME" > /dev/null
cd "$BASENAME"

# Lets ensure the permissions allow us to pack everything
chmod 777 -R ./*

# Remove unwanted files
CBRTHUMBS=`find */Thumbs.db 2>/dev/null`
[[ ! -z "$CBRTHUMBS" ]] && rm $CBRTHUMBS && echo "--> Trashed Thumbs.db"

CBRSTORE=`find */.DS_Store 2>/dev/null`
[[ ! -z "$CBRSTORE" ]] && rm $CBRSTORE && echo "--> Trashed .DS_Store"

CBRSCANNER=`find -type f -iname 'z*.jpg' 2>/dev/null`
[[ ! -z "$CBRSCANNER" ]] && echo "--> Found scan credits" && rm $CBRSCANNER

echo "-> Compressing"
7z a -tzip -mx=9 "$NEWNAME" * > /dev/null

# And move it to the directory where we found the original ".cbr" file
mv "$NEWNAME" "$DIRNAME"

echo "--> Cleaning up"
cd ..
rm -r "$BASENAME"
rm "$CBRFILE"

done

cd ..
rm -r "$TEMPDIR"
echo
echo "=> Conversion Done"

echo
CBDID=$(cat comic.log |grep -c -i "Processing")
CBFND=$(cat comic.log |grep -c -i "Found scan credits")
echo "+ Processed $CBDID files"
echo "+ Found $CBFND scan credits"
echo
