#!/bin/bash

SOURCEDIR=`pwd`
IFS="|"
TEMPDIR=".r2z_tmp"

case $1 in

    -z|--zip)
        CBFORMAT=".cbz"
    ;;
    -t|--tar)
        CBFORMAT=".cbt"
    ;;
    *)
        CBFORMAT=".cbr"
    ;;

esac

# Log STOUT to file
[[ -f "comic.log" ]] && rm "comic.log"
exec > >(tee comic.log)

clear
echo
echo "+ Working from directory $SOURCEDIR"

cd "$SOURCEDIR"
[[ -d "$TEMPDIR" ]] && rm -rf $TEMPDIR
mkdir "$TEMPDIR" && cd "$TEMPDIR"

find "$SOURCEDIR" -name "*$CBFORMAT" | while read CBRFILE; do
BASENAME=`basename $CBRFILE $CBFORMAT`
DIRNAME=`dirname $CBRFILE`
NEWNAME="$BASENAME.cbz"

echo
echo "> Processing: $BASENAME"
mkdir "$BASENAME"
echo "-> Extracting"
7z x "$CBRFILE" -O"$BASENAME" > /dev/null
cd "$BASENAME"

# Lets ensure the permissions allow us to pack everything
chmod 777 -R ./*

# Remove unwanted files
CBRSCANNER=`find -type f -iname 'z*.*' 2>/dev/null`
[[ ! -z "$CBRSCANNER" ]] && echo "--> Found scan credits" && rm $CBRSCANNER || echo "--> No matches found"

CBRTHUMBS=`find */Thumbs.db 2>/dev/null`
[[ ! -z "$CBRTHUMBS" ]] && rm $CBRTHUMBS && echo "--> Trashed Thumbs.db"

CBRSTORE=`find */.DS_Store 2>/dev/null`
[[ ! -z "$CBRSTORE" ]] && rm $CBRSTORE && echo "--> Trashed .DS_Store"

echo "-> Compressing"
7z a -tzip -mx=9 "$NEWNAME" * > /dev/null

# And move it to the directory where we found the original file
mv "$NEWNAME" "$DIRNAME"

echo "--> Cleaning up"
cd ..
rm -r "$BASENAME"

if [ "$CBFORMAT" != ".cbz" ]; then
rm "$CBRFILE"
fi

done

cd ..
rm -r "$TEMPDIR"
echo
echo "=> Conversion Done"

echo
CBDID=$(cat comic.log |grep -c -i "Processing")
CBFND=$(cat comic.log |grep -c -i "Found scan credits")
CBNOT=$(cat comic.log |grep -c -i "No matches found")
CBMSD=$(cat comic.log |grep -B 2 -i "No matches found" |grep "Processing" |cut -c 15-$NF)
[[ ! -z "$CBMSD" ]] && echo $CBMSD > missed_files.log
echo "+ $CBDID files processed"
echo "+ $CBFND scan credits found"
echo "+ $CBNOT missed files logged"
echo
