#!/bin/bash

SOURCE=$(pwd)
TEMP=".cb_tmp"
INPUT="cbr"
OUTPUT="cbz"
IFS="|"
FORMAT=

while getopts s:i:o:q opt; do
	case $opt in
	s)
		SOURCE=$OPTARG
		;;
	i)
		INPUT=$OPTARG
		;;
	o)
		OUTPUT=$OPTARG
		;;
	q)
		QUIET="1"
		;;
	esac
done

shift $((OPTIND - 1))

if [ "$QUIET" == "1" ]; then
CBLDIR="/tmp"; else
CBLDIR="$SOURCE"
fi

if [ "$OUTPUT" == "cbz" ]; then
FORMAT="zip"
elif [ "$OUTPUT" == "cbt" ]; then
FORMAT="tar"
elif [ "$OUTPUT" == "cb7" ]; then
FORMAT="7z"; else
echo "+ Output format is not supported"
echo && exit 0
fi

clear
cd "$SOURCE"
CBLOG="$CBLDIR/comvert.log"
[[ -f "$CBLOG" ]] && rm "$CBLOG"
exec > >(tee "$CBLOG")

echo "+ Working from $SOURCE"

[[ -d "$TEMP" ]] && rm -rf "$TEMP"
mkdir "$TEMP" && cd "$TEMP"

find "$SOURCE" -name "*.$INPUT" | while read CBFILE; do
BASENAME=`basename "$CBFILE" .$INPUT`
DIRNAME=`dirname "$CBFILE"`
NEWNAME="$BASENAME.$OUTPUT"

echo
echo "> Processing: $BASENAME"
mkdir "$BASENAME"
echo "-> Extracting"
7z x "$CBFILE" -O"$BASENAME" > /dev/null
cd "$BASENAME"

# Remove unwanted files
CBSCAN=`find -type f -iname "z*.*" 2>/dev/null`
[[ ! -z "$CBSCAN" ]] && echo "--> Found scan credits" && rm $CBSCAN || echo "--> No matches found"

CBTHUMBS=`find */Thumbs.db 2>/dev/null`
[[ ! -z "$CBTHUMBS" ]] && rm $CBTHUMBS && echo "--> Trashed Thumbs.db"

CBSTORE=`find */.DS_Store 2>/dev/null`
[[ ! -z "$CBSTORE" ]] && rm $CBSTORE && echo "--> Trashed .DS_Store"

echo "-> Compressing"
7z a -t$FORMAT "$NEWNAME" * > /dev/null

mv "$NEWNAME" "$DIRNAME"

echo "--> Cleaning up"
cd ..
rm -r "$BASENAME"

if [ "$INPUT" != "$OUTPUT" ]; then
rm "$CBFILE"
fi

done
cd ..
rm -r "$TEMP"
echo
echo "=> Conversion Done"
echo
CBDID=$(cat "$CBLOG" |grep -c -i "Processing")
CBFND=$(cat "$CBLOG" |grep -c -i "Found scan credits")
CBNOT=$(cat "$CBLOG" |grep -c -i "No matches found")
CBMSD=$(cat "$CBLOG" |grep -B 2 -i "No matches found" |grep "Processing" |cut -c 15-$NF)
[[ ! -z "$CBMSD" ]] && echo $CBMSD > "$SOURCE/missed_files.log"
echo "+ $CBDID files processed"
echo "+ $CBFND scan credits found"
echo "+ $CBNOT missed files logged"
echo
