#!/bin/bash

SOURCE=$(pwd)
TEMP=".cb_tmp"
INPUT=cbr
OUTPUT=cbz
TYPE=

while getopts s:i:o: opt; do
	case $opt in
	s)
		SOURCE=$OPTARG
		;;
	i)
		INPUT=$OPTARG
		;;
	o)
		OUTPUT=$OPTARG
		;;
	esac
done

shift $((OPTIND - 1))

if [ "$OUTPUT"=="cbz" ]; then
TYPE="zip"
elif [ "$OUTPUT"=="cbt" ]; then
TYPE="tar"
elif [ "$OUTPUT"=="cbr" ]; then
TYPE="rar"
fi

clear
echo
echo "+ Working from $SOURCE"
cd "$SOURCE" && SOURCE=$(pwd)
[[ -d "$TEMP" ]] && rm -rf "$TEMP"
mkdir "$TEMP" && cd "$TEMP"

find "$SOURCE" -name "*.$INPUT" | while read CBFILE; do
BASENAME=`basename "$CBFILE" .$INPUT`
DIRNAME=`dirname "$CBFILE"`
NEWNAME="$BASENAME.$OUTPUT"

echo
echo "> Processing: $BASENAME"
mkdir "$BASENAME"
echo "-> Extracting"
7z x "$CBFILE" -O"$BASENAME" > /dev/null
cd "$BASENAME"

# Remove unwanted files
CBRSCANNER=`find -type f -iname 'z*.*' 2>/dev/null`
[[ ! -z "$CBSCAN" ]] && echo "--> Found scan credits" && rm $CBSCAN || echo "--> No matches found"

CBRTHUMBS=`find */Thumbs.db 2>/dev/null`
[[ ! -z "$CBTHUMBS" ]] && rm $CBTHUMBS && echo "--> Trashed Thumbs.db"

CBRSTORE=`find */.DS_Store 2>/dev/null`
[[ ! -z "$CBSTORE" ]] && rm $CBSTORE && echo "--> Trashed .DS_Store"

echo "-> Compressing"
7z a -t$TYPE "$NEWNAME" * > /dev/null

mv "$NEWNAME" "$DIRNAME"

echo "--> Cleaning up"
cd ..
rm -r "$BASENAME"

if [ "$INPUT" != "$OUTPUT" ]; then
rm "$CBFILE"
fi

done
cd ..
rm -rf "$TEMP"
echo
echo "=> Conversion Done"
