#!/bin/bash

## User Variables
TEMP="/tmp"
INST="/opt/comvert" # Set directory to the blacklist

## Default Options
SOURCE=$(pwd)
INPUT="cbr"
OUTPUT="cbz"

## Comvert Variables
LOG="$TEMP/comvert.log"
LIST="$INST/blacklist.ini"
WORK="$SOURCE/.cb_tmp"
SUSP="$SOURCE/suspicious_files.txt"

## START
while getopts s:i:o:q opt; do
	case $opt in
	s)
		SOURCE=$OPTARG
		;;
	i)
		INPUT=$OPTARG
		;;
	o)
		OUTPUT=$OPTARG
		;;
	esac
done

shift $((OPTIND - 1))

if [ "$OUTPUT" == "cbz" ]; then
	FORMAT="zip"
elif [ "$OUTPUT" == "cbt" ]; then
	FORMAT="tar"
elif [ "$OUTPUT" == "cb7" ]; then
	FORMAT="7z"; else
		echo "+ Output format is not supported"
		echo && exit 1
fi

[[ -f "$LOG" ]] && rm "$LOG"
touch "$LOG" 2>/dev/null || { echo "+ Access denied to $TEMP"; exit 1; }

[[ -d "$WORK" ]] && rm -rf "$WORK"
mkdir "$WORK" 2>/dev/null || { echo "+ Access denied to $SOURCE"; exit 1; }

clear && exec > >(tee "$LOG")
cd "$SOURCE" && echo "+ Working from $SOURCE"
echo

## Convert Loop
find "$SOURCE" -name "*.$INPUT" | while read CBFILE; do
BASENAME=`basename "$CBFILE" .$INPUT`
DIRNAME=`dirname "$CBFILE"`
NEWNAME="$BASENAME.$OUTPUT"

echo "> Processing: $BASENAME" && mkdir "$BASENAME"
echo "-> Extracting" && 7z x "$CBFILE" -O"$BASENAME" >/dev/null && cd "$BASENAME"

echo "--> Scanning"

while read CBSCAN; do
	CBCRED=`find -type f -iname "$CBSCAN"`
	[[ ! -z "$CBCRED" ]] && rm "$CBCRED" && echo "---> Removed Blacklisted File"
done < "$LIST"

CBSCAN=`find -type f -iname "[x-z]*"`
if [ ! -z "$CBSCAN" ]; then
	echo "$BASENAME" >> "$SUSP"
	echo "$CBSCAN" >> "$SUSP"
	echo "|" >> "$SUSP"
	echo "---> Suspicious Files Logged!"
fi

echo "-> Compressing" && 7z a -t$FORMAT "$NEWNAME" * > /dev/null
mv "$NEWNAME" "$DIRNAME"

echo "> Cleaning up" && cd .. && rm -r "$BASENAME"
echo

## Dont delete the new file if it has the same name
[[ "$INPUT" != "$OUTPUT" ]] &&	rm "$CBFILE"
done

cd .. && rm -r "$WORK" && echo "=> Conversion Done"
echo

CBDID=$(cat "$LOG" |grep -c -i "Processing") && echo "+ $CBDID archives processed"
CBFND=$(cat "$LOG" |grep -c -i "Blacklisted") && echo "+ $CBFND files removed"
CBMSD=$(cat "$LOG" |grep -c -i "Suspicious") && echo "+ $CBMSD suspicious archives"
echo

#notify-send Comvert "Sir, your comics are done"
